name: Create new release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Create new release
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/hybrid-cloud-postgresql-operator
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          TAG=${GITHUB_REF//refs\/tags\/v}
          docker build . -t $IMAGE_ID:$TAG
          docker push $IMAGE_ID:$TAG

      - name: Prepare helm chart
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          VERSION=${GITHUB_REF//refs\/tags\/v}
          sed -i 's/0.0.1/'"${VERSION}"'/' helm/hybrid-cloud-postgresql-operator/Chart.yaml
          sed -i 's/0.1.0/'"${VERSION}"'/' helm/hybrid-cloud-postgresql-operator/Chart.yaml
          sed -i 's/dev/'"${VERSION}"'/' helm/hybrid-cloud-postgresql-operator/values.yaml
          sed -i 's/0.0.1/'"${VERSION}"'/' helm/hybrid-cloud-postgresql-operator-crds/Chart.yaml
          sed -i 's/0.1.0/'"${VERSION}"'/' helm/hybrid-cloud-postgresql-operator-crds/Chart.yaml

      - name: Publish helm chart
        uses: stefanprodan/helm-gh-pages@0ad2bb377311d61ac04ad9eb6f252fb68e207260 # v1.7.0
        with:
          charts_dir: helm
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
